version: '3.8'

services:
  mysql:
    image: mysql:8.0.1
    container_name: smhospitaldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: smhospitaldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:

